sudo: false
language: ruby
before_install: gem install bundler
rvm:
  - 2.3
  - 2.4
notifications:
  email:
    on_success: never
  slack:
    secure: kcRMRU/epqsBn3n0McTz0RdGSR07xhyz5g6jOfufA1bRlmLsIQtIaeqeO0VLtcQFUd5JJ1Z2iVz9YdvbA0RLeXwI0ZS96g9NWZn1TFBk6zMM8/CN4kZcWcPKO9INbBMziRlF7lb039CRrusE0ei1YJLojPGWnsKITcS88rSX+Uq0wPDaN6nEzQbDU2HV3TBl31W0LlYYpcmz6Ju9HGVdU1NrA0DRbeV78YmUkyJ4v6p8pgOaKKx+oZidUQmjvBIuBcko9VayXnncg4NQZWG4c6A5keLEFHzgOpSEgu+NnHsTz5ILT2AtysNxC8UJ5dYc7hR/qXsB9Z6ZJjRc+oGTXq6j58f153AW+2R4Mtx7Lp2zg+JeqYO34riu8vnihBk5rNsuHNcz3+ipmePjBt6emmJVpMxleWs9JFpbxXm3JnaSQZtUqALqvs6ZL9gxxokQcy4xbD8BJFvhYpc3b2464JPJhK7LNDNobTv4LdG6m6KSzTnN//zNuE5hSQhMbjo9mnYWN7V9n3asi1EsEpIYqpjRJnlNVDwTdW0jJ7wUSNPdEvSL7g1lDqgJTUuNBh/stpXh6nA8Um5ZxU3cAuuX7VwnDqIdaw81UnkGIlYWBFYMMR2p03y7EaTMZafKWKEcS6LJsv7yIjtfHJgf45LkIHceEj++8JEOKItvDYWHOL4=
